[package]
name = "caspervk-chess-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.9.3"
chess-lib = { git = "https://github.com/INDA24PlusPlus/eskilny-chess" }
chess-networking = { git = "https://github.com/INDA24PlusPlus/chess-networking" }
serde = "1.0.210"
rmp-serde = "1.3.0"
