[package]
name = "caspervk-chess-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.9.3"
arvidkr_chess = { git = "https://github.com/INDA24PlusPlus/arvidkr-chess" }
oorandom = "11.1.4"
